### ISSUE TITLE
Latest vim

### ISSUE THREAD

**Issue by Maxim-Filimonov** [nitrous-io/autoparts#10]
Not sure that it is a good case for autoparts but some plugins like https://github.com/Valloric/YouCompleteMe 
requires more recent version of vim than the one which comes with ubuntu. 

Not sure how to contribute a package because most packages are using binary path which is nitrous s3. Is there a way to upload it there somehow?
Commands i've run to compile the latest vim on a nitrobox

``` bash
hg clone https://vim.googlecode.com/hg/ vim
cd vim
./configure --with-features=huge
make
```

The only thing left here is to add the new vim to the PATH to replace the old one. 
Which might be an interesting issue because usually it's done using `sudo make install` which I can't ran on the box due to lack of sudo permissions.

**Comment by danmarg** [comment]
$ parts list|grep vim                                                                                            
vim (7.4.335)
$ which vim                                                                                                      
/home/action/.parts/bin/vim
$ vim --version                                                                                                  
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul  7 2014 02:26:57)
Included patches: 1-335
Compiled by Nitrous.IO
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       -python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/home/action/.parts/packages/vim/7.4.335/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -ldl          
$ vim                                                                                                            
YouCompleteMe unavailable: requires Vim compiled with Python 2.x support
Press ENTER or type command to continue
