### ISSUE TITLE
ghc doesn't work

### ISSUE THREAD

**Issue by danmarg** [nitrous-io/autoparts#231]
$ ghci
GHCi, version 7.8.3: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... <command line>: can't load .so/.DLL for: libgmp.so (libgmp.so: cannot open shared object file: No such file or directory)

**Comment by gmckeever** [comment]
Can you try this on a new box after installing ghc again? I tested this out and wasn't able to reproduce the issue.

**Comment by danmarg** [comment]
I guess you have LD_LIBRARY_PATH set to $HOME/.parts/lib. That fixes it.
