### ISSUE TITLE
Unable to install PostgreSQL

### ISSUE THREAD

**Issue by dwanjuhi1** [nitrous-io/autoparts#239]
This is the error message returned:

action@hasty-dagger-82-183319:~/rails_rss_reader(master)$ parts install postgresql                                                                                                                                  
=> Downloading http://parts.nitrous.io/postgresql-9.3.5-binary.tar.gz...                                                                                                                                            
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                                                                     
                                 Dload  Upload   Total   Spent    Left  Speed                                                                                                                                       
100    41  100    41    0     0   1108      0 --:--:-- --:--:-- --:--:--  2157                                                                                                                                      
(23) Failed writing body                                                                                                                                                                                            
parts: ERROR: "curl http://parts.nitrous.io/postgresql-9.3.5-binary.sha1 -L -o /home/action/.parts/tmp/postgresql-9.3.5-binary.sha1.partsdownload" failed                                                           
Aborting!

**Comment by gmckeever** [comment]
I've tested this on another box and it installed successfully, and I'm thinking you may have ran out of disk space. Could you check your available disk space on the box settings page? You may want to increase your disk space to 2 or 3GB before trying again.

http://help.nitrous.io/box-settings/

**Comment by dwanjuhi1** [comment]
Thank you. Increasing my disk space solved the problem.
